### ISSUE TITLE
Turtlebot Waffle

### ISSUE THREAD

**Issue by florianspy** [ROBOTIS-GIT/emanual#322]
Dear Sirs,
I have a short question regarding change of the design of the waffle.
If i elevate the third layer what software changes regarding the lidar sensor has to be done? Is there a parameter to specify its height?

sincerely yours,
Florian Spieß

**Comment by ROBOTIS-Will** [comment]
Hello, Florian

Thank you for the inquiry.
I assume that you will need to modify your robot description files in order to reflect the changes in the 3D simulation/visualization tool.
[https://github.com/ROBOTIS-GIT/turtlebot3/tree/master/turtlebot3_description](https://github.com/ROBOTIS-GIT/turtlebot3/tree/master/turtlebot3_description)
For the TurtleBot3 related questions, it might be easier for you to get an answer from ROS community.
Here's the link for you.
[https://answers.ros.org/questions/](https://answers.ros.org/questions/)
As this question is not related to the contents of the eManual, I'll close this thread.
Thank you.
