### ISSUE TITLE
Unbale to locate package when installed Additional Dependent Packages for AutoRace on Pi

### ISSUE THREAD

**Issue by Ethanaiot** [ROBOTIS-GIT/emanual#578]
Hi,

 When I installed Additional Dependent Packages for AutoRace on Pi, it has the following issues . Could you please advise how can I fix it?

pi@raspberrypi:~$ sudo apt-get install ros-kinetic-image-transport ros-kinetic-cv-bridge ros-kinetic-vision-opencv python-opencv libopencv-dev ros-kinetic-image-proc
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ros-kinetic-image-transport
E: Unable to locate package ros-kinetic-cv-bridge
E: Unable to locate package ros-kinetic-vision-opencv
E: Unable to locate package ros-kinetic-image-proc

**Comment by Ethanaiot** [comment]
Hi Gilbert,
Could you please help? Thank you in advance!!

Regards,
Ethan

**Comment by ROBOTIS-Will** [comment]
Hi @Ethanaiot ,
Looks like dependent packages are not installed.
Have you try to reinstall those packages that are not installed properly?

**Comment by Ethanaiot** [comment]
Hi Will,  thanks for your reply.

We have terminated the project. Please ignore the issue.
If it is reopened and I still meet the same issue, ill let you know. Thank
you.

Regards,
Ethan

Will Son <notifications@github.com> 於 2018年12月17日 週一 15:39寫道：

**Comment by imostafizur** [comment]
Please check your ROS version using this command **rosversion -d**.
After that run sudo apt-get install ros-**version_name-**image-transport ros-**version_name**-cv-bridge ros-**version_name-**vision-opencv python-opencv libopencv-dev ros-**version_name**-image-proc.

**Comment by amakil76** [comment]
I'm having the same problems as the top first questions. The pi is using the image provide by your website (Ros kinetic  for Pi 3b+). Is this because the Kinetic is no longer supported ?

pi@raspberrypi:~ $ sudo apt-get install ros-kinetic-image-transport ros-kinetic-cv-bridge ros-kinetic-vision-opencv python-opencv libopencv-dev ros-kinetic-image-pro
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-kinetic-image-transport
E: Unable to locate package ros-kinetic-cv-bridge
E: Unable to locate package ros-kinetic-vision-opencv
E: Unable to locate package ros-kinetic-image-pro
pi@raspberrypi:~ $
